/* ============================================================
   Species Map — Single Source of Truth
   Common animal name (lowercase) → scientific name mapping.

   USAGE:
     App.speciesMap['lion']  // → 'Panthera leo'

   Previously duplicated in:
     - data.js       (_speciesMap)
     - animal-info.js (_speciesMap)
   Now unified here. Both modules reference App.speciesMap.
   ============================================================ */
var App = window.App || {};

App.speciesMap = {
  /* ── Mammals ─────────────────────────────────────────────── */
  'lion':             'Panthera leo',
  'lioness':          'Panthera leo',
  'tiger':            'Panthera tigris',
  'elephant':         'Loxodonta africana',
  'asian elephant':   'Elephas maximus',
  'giant panda':      'Ailuropoda melanoleuca',
  'panda':            'Ailuropoda melanoleuca',
  'red panda':        'Ailurus fulgens',
  'snow leopard':     'Panthera uncia',
  'cheetah':          'Acinonyx jubatus',
  'jaguar':           'Panthera onca',
  'mountain lion':    'Puma concolor',
  'giraffe':          'Giraffa camelopardalis',
  'zebra':            'Equus quagga',
  'hippopotamus':     'Hippopotamus amphibius',
  'rhinoceros':       'Ceratotherium simum',
  'gorilla':          'Gorilla gorilla',
  'chimpanzee':       'Pan troglodytes',
  'orangutan':        'Pongo pygmaeus',
  'monkey':           'Primates',
  'howler monkey':    'Alouatta',
  'polar bear':       'Ursus maritimus',
  'grizzly bear':     'Ursus arctos horribilis',
  'brown bear':       'Ursus arctos',
  'bear':             'Ursidae',
  'sun bear':         'Helarctos malayanus',
  'wolf':             'Canis lupus',
  'coyote':           'Canis latrans',
  'dingo':            'Canis lupus dingo',
  'red fox':          'Vulpes vulpes',
  'dolphin':          'Tursiops truncatus',
  'blue whale':       'Balaenoptera musculus',
  'orca':             'Orcinus orca',
  'seal':             'Pinnipedia',
  'leopard seal':     'Hydrurga leptonyx',
  'kangaroo':         'Macropus',
  'wallaby':          'Macropus agilis',
  'koala':            'Phascolarctos cinereus',
  'platypus':         'Ornithorhynchus anatinus',
  'wombat':           'Vombatus ursinus',
  'tasmanian devil':  'Sarcophilus harrisii',
  'capybara':         'Hydrochoerus hydrochaeris',
  'jaguar':           'Panthera onca',
  'sloth':            'Bradypus tridactylus',
  'llama':            'Lama glama',
  'vampire bat':      'Desmodus rotundus',
  'moose':            'Alces alces',
  'elk':              'Cervus canadensis',
  'reindeer':         'Rangifer tarandus',
  'sambar deer':      'Rusa unicolor',
  'bison':            'Bison bison',
  'european bison':   'Bison bonasus',
  'lynx':             'Lynx lynx',
  'badger':           'Meles meles',
  'otter':            'Lutrinae',
  'beaver':           'Castor canadensis',
  'raccoon':          'Procyon lotor',
  'wild boar':        'Sus scrofa',
  'horse':            'Equus ferus caballus',
  'rabbit':           'Leporidae',
  'hedgehog':         'Erinaceidae',
  'cat':              'Felis catus',
  'kitten':           'Felis catus',

  /* ── Birds ───────────────────────────────────────────────── */
  'eagle':            'Aquila chrysaetos',
  'bald eagle':       'Haliaeetus leucocephalus',
  'penguin':          'Aptenodytes forsteri',
  'flamingo':         'Phoenicopterus roseus',
  'parrot':           'Psittaciformes',
  'macaw':            'Ara macao',
  'toucan':           'Ramphastos toco',
  'peacock':          'Pavo cristatus',
  'emu':              'Dromaius novaehollandiae',
  'kookaburra':       'Dacelo novaeguineae',
  'albatross':        'Diomedeidae',
  'arctic tern':      'Sterna paradisaea',
  'snow petrel':      'Pagodroma nivea',
  'butterfly':        'Lepidoptera',

  /* ── Reptiles ────────────────────────────────────────────── */
  'sea turtle':       'Chelonia mydas',
  'turtle':           'Chelonia mydas',
  'leatherback turtle': 'Dermochelys coriacea',
  'tortoise':         'Testudinidae',
  'galapagos tortoise': 'Chelonoidis niger',
  'komodo dragon':    'Varanus komodoensis',
  'monitor lizard':   'Varanidae',
  'chameleon':        'Furcifer pardalis',
  'gecko':            'Gekkota',
  'iguana':           'Iguanidae',
  'crocodile':        'Crocodylidae',
  'alligator':        'Alligator mississippiensis',
  'anaconda':         'Eunectes murinus',
  'python':           'Pythonidae',
  'rattlesnake':      'Crotalus',
  'king cobra':       'Ophiophagus hannah',
  'coral snake':      'Micrurus',
  'tuatara':          'Sphenodon punctatus',
  'gila monster':     'Heloderma suspectum',

  /* ── Amphibians ──────────────────────────────────────────── */
  'tree frog':        'Hylidae',
  'frog':             'Anura',
  'toad':             'Bufonidae',
  'bullfrog':         'Lithobates catesbeianus',
  'newt':             'Pleurodelinae',
  'salamander':       'Caudata',
  'axolotl':          'Ambystoma mexicanum',
  'poison dart frog': 'Dendrobatidae',
  'red eyed tree frog': 'Agalychnis callidryas',
  'glass frog':       'Centrolenidae',
  'hellbender':       'Cryptobranchus alleganiensis',
  'caecilian':        'Gymnophiona',

  /* ── Aquatic / Marine ────────────────────────────────────── */
  'great white shark': 'Carcharodon carcharias',
  'shark':            'Carcharodon carcharias',
  'octopus':          'Enteroctopus dofleini',
  'manta ray':        'Manta birostris',
  'clownfish':        'Amphiprioninae',
  'jellyfish':        'Scyphozoa',
  'seahorse':         'Hippocampus',
  'coral':            'Anthozoa',
  'piranha':          'Serrasalmus',
  'squid':            'Teuthida',
  'krill':            'Euphausiacea'
};
